<?php
function adimeo_drupal_monitoring_cron()
{
  /** @var \Drupal\adimeo_drupal_monitoring\Manager\MonitoringManager $monitoringManager */
    $monitoringManager = \Drupal::service('adimeo_drupal_monitoring.processing.manager');

  /** @var \Drupal\adimeo_drupal_monitoring\Manager\SendingManager $sendingManager */
  $sendingManager = \Drupal::service('adimeo_drupal_monitoring.sending.manager');

  // Only work one time per day, wait for the day to change
  if ($monitoringManager->shouldRunCron()) {
    $data = $monitoringManager->fetchData();

    $config = \Drupal::config('adimeo_drupal_monitoring.config');

    if ($config->get('drupal_monitoring_sending_method') === 'api') {
      $sendingManager->sendApi($data);
    } else {
      $sendingManager->sendEmail($data);
    }
  }

}